### PR TITLE
Fix backend ref conf

### LINKED ISSUE #189: Request with referenced backend fails
**Describe the bug**
The request backend configuration seems to fail if the backend string reference is used.

**To Reproduce**
1. Which Couper version? Run `couper version` or `docker run --entrypoint=/couper avenga/couper version`
`0.8 2021-04-08 2a27495`
2. Provide your configuration file `*.hcl`. Remove sensitive data.
```hcl
server "couper" {

  endpoint "/" {
    request {
      backend = "ref"
    }
  }
}

definitions {
  backend "ref" {
    origin = "https://httpbin.org"
  }
}
```
3. Provide a `curl` call for reproduction
`curl -v http://localhost:8080/`
4. See an error response or error log.
`ERRO[0018] connecting to default ":80" failed: dial tcp :80: connect: connection refused`

**Expected behavior**
Connect and request https://httpbin.org/

### PR DESCRIPTION
**Pull request by malud**
Closes #189 

- [x] Test

### CODE REVIEW

File: config/oauth2.go [hunk 1]
```diff
@@ -29,7 +32,7 @@ func (oa OAuth2) HCLBody() hcl.Body {
 
 // Reference implements the <Inline> interface.
 func (oa OAuth2) Reference() string {
-	return "OAuth2"
+	return oa.BackendName
```
Comment (alex-schneider) [inline config/oauth2.go:35]: `if oa.BackendName == "" { return "OAuth2" } else { return oa.BackendName }`?

Comment (malud) [reply config/oauth2.go:35]: Since this would be for logging purposes only the current `token_request` log field should be ok for now.

**Review by alex-schneider — APPROVED** [review]
