### PR TITLE
watch with double go routines

### LINKED ISSUE #692: `NewServerConfiguration()` called twice after config reload with `-watch` causing e.g. double health probes/jobs
With `-watch`, after a config reload,
* the probe is shut down later than the server, and
* I get two health probes.

Example:
```hcl
server {
  hosts = ["*:8080"]
  endpoint "/" {
    proxy {
      backend = "be"
    }
  }
}

definitions {
  backend "be" {
    origin = "https://blackhole.webpagetest.org"
    beta_health {
      interval = "10s"
      timeout = "3s"  
    }
  }
}
```
Start Couper
```
INFO[0000] watching configuration file(s)                build=dev type=couper_daemon version=0 watch="map[max-retries:5 retry-delay:500ms]"
INFO[0000] ulimit: max open files: 1048576 (hard limit: 1048576)  build=dev type=couper_daemon version=0
INFO[0000] couper is serving: 0.0.0.0:8080               build=dev type=couper_daemon version=0
```
Normal health check:
```
ERRO[0000] backend error: context deadline exceeded      backend=be build=dev custom="map[]" error_type=backend method=GET request="map[headers:map[user-agent:Couper / 0 health-check] host:blackhole.webpagetest.org method:GET name:health-check origin:blackhole.webpagetest.org path: proto:https]" status=0 timings="map[dns:20.997 total:3000.255]" type=couper_backend uid=cfcjk5beg9scfeq3hfig url="https://blackhole.webpagetest.org" version=0
WARN[0003] new health state: failing                     backend=be build=dev type=couper_daemon uid=cfcjk5beg9scfeq3hfig url="https://blackhole.webpagetest.org" version=0
```
Reload config:
```
INFO[0008] reloading couper configuration                build=dev type=couper_daemon version=0
INFO[0008] ulimit: max open files: 1048576 (hard limit: 1048576)  build=dev type=couper_daemon version=0
ERRO[0008] retry 1/5 due to listen error: listen tcp4 :8080: bind: address already in use  build=dev type=couper_daemon version=0
WARN[0008] shutting down                                 build=dev deadline=0s delay=0s type=couper_daemon version=0
INFO[0008] http: Server closed: 0.0.0.0:8080             build=dev type=couper_daemon version=0
INFO[0008] ulimit: max open files: 1048576 (hard limit: 1048576)  build=dev type=couper_daemon version=0
INFO[0008] couper is serving: 0.0.0.0:8080               build=dev type=couper_daemon version=0
```
Double health check log:
```
ERRO[0008] backend error: context deadline exceeded      backend=be build=dev custom="map[]" error_type=backend method=GET request="map[headers:map[user-agent:Couper / 0 health-check] host:blackhole.webpagetest.org method:GET name:health-check origin:blackhole.webpagetest.org path: proto:https]" status=0 timings="map[dns:24.815 total:3000.822]" type=couper_backend uid=cfcjk7beg9scfeq3hfj0 url="https://blackhole.webpagetest.org" version=0
WARN[0011] new health state: failing                     backend=be build=dev type=couper_daemon uid=cfcjk7beg9scfeq3hfj0 url="https://blackhole.webpagetest.org" version=0
ERRO[0008] backend error: context deadline exceeded      backend=be build=dev custom="map[]" error_type=backend method=GET request="map[headers:map[user-agent:Couper / 0 health-check] host:blackhole.webpagetest.org method:GET name:health-check origin:blackhole.webpagetest.org path: proto:https]" status=0 timings="map[dns:20.787 total:3000.621]" type=couper_backend uid=cfcjk7beg9scfeq3hfjg url="https://blackhole.webpagetest.org" version=0
WARN[0011] new health state: failing                     backend=be build=dev type=couper_daemon uid=cfcjk7beg9scfeq3hfjg url="https://blackhole.webpagetest.org" version=0
```
Health probe shutdown log:
```
WARN[0013] shutdown health probe                         backend=be build=dev type=couper_daemon url="https://blackhole.webpagetest.org" version=0
```
Still double health check logs:
```
ERRO[0021] backend error: context deadline exceeded      backend=be build=dev custom="map[]" error_type=backend method=GET request="map[headers:map[user-agent:Couper / 0 health-check] host:blackhole.webpagetest.org method:GET name:health-check origin:blackhole.webpagetest.org path: proto:https]" status=0 timings="map[dns:20.353 total:3000.917]" type=couper_backend uid=cfcjkajeg9scfeq3hfk0 url="https://blackhole.webpagetest.org" version=0
ERRO[0024] backend error: backend error: connecting to be 'blackhole.webpagetest.org' failed: i/o timeout: new health state: unhealthy  backend=be build=dev error_type=backend_unhealthy type=couper_daemon uid=cfcjkajeg9scfeq3hfk0 url="https://blackhole.webpagetest.org" version=0
ERRO[0021] backend error: context deadline exceeded      backend=be build=dev custom="map[]" error_type=backend method=GET request="map[headers:map[user-agent:Couper / 0 health-check] host:blackhole.webpagetest.org method:GET name:health-check origin:blackhole.webpagetest.org path: proto:https]" status=0 timings="map[dns:23.634 total:3000.681]" type=couper_backend uid=cfcjkajeg9scfeq3hfkg url="https://blackhole.webpagetest.org" version=0
ERRO[0024] backend error: backend error: connecting to be 'blackhole.webpagetest.org' failed: i/o timeout: new health state: unhealthy  backend=be build=dev error_type=backend_unhealthy type=couper_daemon uid=cfcjkajeg9scfeq3hfkg url="https://blackhole.webpagetest.org" version=0
```
```
ERRO[0034] backend error: context deadline exceeded      backend=be build=dev custom="map[]" error_type=backend method=GET request="map[headers:map[user-agent:Couper / 0 health-check] host:blackhole.webpagetest.org method:GET name:health-check origin:blackhole.webpagetest.org path: proto:https]" status=0 timings="map[dns:27.049 total:3000.152]" type=couper_backend uid=cfcjkdreg9scfeq3hfl0 url="https://blackhole.webpagetest.org" version=0
ERRO[0034] backend error: context deadline exceeded      backend=be build=dev custom="map[]" error_type=backend method=GET request="map[headers:map[user-agent:Couper / 0 health-check] host:blackhole.webpagetest.org method:GET name:health-check origin:blackhole.webpagetest.org path: proto:https]" status=0 timings="map[dns:21.148 total:3000.795]" type=couper_backend uid=cfcjkdreg9scfeq3hflg url="https://blackhole.webpagetest.org" version=0
```
```
ERRO[0047] backend error: context deadline exceeded      backend=be build=dev custom="map[]" error_type=backend method=GET request="map[headers:map[user-agent:Couper / 0 health-check] host:blackhole.webpagetest.org method:GET name:health-check origin:blackhole.webpagetest.org path: proto:https]" status=0 timings="map[dns:20.394 total:3000.424]" type=couper_backend uid=cfcjkh3eg9scfeq3hfm0 url="https://blackhole.webpagetest.org" version=0
ERRO[0047] backend error: context deadline exceeded      backend=be build=dev custom="map[]" error_type=backend method=GET request="map[headers:map[user-agent:Couper / 0 health-check] host:blackhole.webpagetest.org method:GET name:health-check origin:blackhole.webpagetest.org path: proto:https]" status=0 timings="map[dns:21.6 total:3000.629]" type=couper_backend uid=cfcjkh3eg9scfeq3hfmg url="https://blackhole.webpagetest.org" version=0
```

### PR DESCRIPTION
**Pull request by alex-schneider**
closes #692 

---
<details>
    <summary>Reviewer checklist</summary>
    <ul>
        <li>Read PR description: a summary about the changes is required</li>
        <li>Changelog updated</li>
        <li>Documentation: docs/{Reference, Cli, ...}, Docker and cli help/usage</li>
        <li>Pulled branch, manually tested</li>
        <li>Verified requirements are met</li>
        <li>Reviewed the code</li>
        <li>Reviewed the related tests</li>
    </ul>
</details>

### CODE REVIEW

**Comment by johakoch** [comment]
handler/transport/probe.go:
```go
	// do not start go-routine on config check (-watch)
	if _, exist := opts.Context.Value(request.ConfigDryRun).(bool); exist {
		return
	}

	if _, exist := tc.Context.Value(request.ConfigDryRun).(bool); !exist {
		go p.probe(opts.Context)
	}
```
Looks like the first part already tries to solve the problem. Why does it not work?

File: handler/transport/probe.go [hunk 1]
```diff
@@ -97,10 +97,9 @@ func NewProbe(log *logrus.Entry, tc *Config, opts *config.HealthCheck, listener
 	}
 
 	// do not start go-routine on config check (-watch)
-	if _, exist := opts.Context.Value(request.ConfigDryRun).(bool); exist {
-		return
+	if _, exist := opts.Context.Value(request.ConfigDryRun).(bool); !exist {
+		go p.probe(opts.Context)
```
Comment (malud) [inline handler/transport/probe.go:101]: I would prefer the exist strategy which applies to job and json routines too.

**Review by malud — CHANGES_REQUESTED** [review]
